# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - BackEndGestor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'  # Mudando para a distribuição temurin

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1  # Adiciona o Gradle Wrapper
        with:
          gradle-version: '7.4'  # A versão do Gradle que você deseja usar

      - name: Build with Gradle
        run: ./gradlew bootJar  # Usando Gradle para compilar o JAR

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/build/libs/*.jar'  # Caminho do JAR gerado pelo Gradle

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BD4ABA76B11F4C4B9253C220E1CC7A11 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E66F3496AAA34F8D9964FE94B6727287 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9BAD2F2001EF4CECBBFFD149F28EC200 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BackEndGestor'
          slot-name: 'Production'
          package: '${{ github.workspace }}/build/libs/*.jar'  # Caminho do JAR gerado
